In [108]:
import numpy as np
import pandas as pd

In [109]:
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

from matplotlib import rc

In [110]:
def get_r2score(model):
    pred = model.predict(X_test)
    score = r2_score(y_test,pred)
    print(model.__class__.__name__, " R2SCORE: ", np.round(score,3))

In [111]:
def get_rmse(model):
    pred = model.predict(X_test)
    mse = mean_squared_error(y_test, pred)
    rmse = np.sqrt(mse)
    print(model.__class__.__name__, ' RMSE: ', np.round(rmse,3))
    return rmse

In [112]:
def get_rmses(models):
    rmses = []
    for model in models:
        rmse = get_rmse(model)
        # rmses.append(rmse)
    # return rmses

In [113]:
def get_r2scores(models):
    scores = []
    for model in models:
        score = get_r2score(model)
        # scores.append(score)
    # return scores

In [114]:
# Preprocessing for turn over rate
def tor_preprocessing(tor):
  tor_df = tor
  tor_val = tor_df['turn_over_rate']

  for i, val in enumerate(tor_val):
    if '정보' in val:
      tor_df.loc[i,'turn_over_rate'] = np.NAN
    elif val == '(9999%)' :
      tor_df.loc[i,'turn_over_rate'] = np.NAN
    elif '(' in val:
      tmp = float(val[1:-1].replace('%',''))*0.01
      tor_df.loc[i,'turn_over_rate'] = tmp

  return tor_df

In [115]:
# Preprocessing for financial variable
def fv_preprocessing(fv):
  fv_df = fv
  afv = fv_df['average_salary']
  tfv = fv_df['total_sale']

  for i, val in enumerate(afv):
    if type(val) == str:
        if '만원' in val:
          tmp = int(val[:-2].replace(',',''))
          fv_df.loc[i,'average_salary'] = tmp
        if '회사' in val:
          fv_df.loc[i,'average_salary'] = np.NAN
        if '수집' in val:
          fv_df.loc[i,'average_salary'] = np.NAN

  for i, val in enumerate(tfv):
    if type(val) == str:
        if '조원' in val:
          tmp = float(val[:-2].replace(',',''))*1000
          fv_df.loc[i,'total_sale'] = tmp
        if '억원' in val:
          tmp = float(val[:-2].replace(',',''))
          fv_df.loc[i,'total_sale'] = tmp
        if '억' in val:
          tmp = float(val[:-1].replace(',',''))
          fv_df.loc[i,'total_sale'] = tmp
          print(fv_df.loc[i,'total_sale'])
          print(i)
        if '회사' in val:
          fv_df.loc[i,'total_sale'] = np.NAN

  return fv_df

In [116]:
df = pd.read_csv("/content/drive/MyDrive/tp_df.csv")
df = df.drop(["Unnamed: 0"], axis=1)
df

,company_name,adv_topic_0,adv_topic_1,adv_topic_2,adv_topic_3,adv_topic_4,adv_topic_5,adv_topic_6,adv_topic_7,adv_topic_8,dadv_topic_0,dadv_topic_1,dadv_topic_2,dadv_topic_3,dadv_topic_4,dadv_topic_5,dadv_topic_6,average_salary,total_sale,turn_over_rate
0,국민건강보험공단,0.946027,0.000000,0.014878,0.000000,0.000000,0.000000,0.000000,0.033859,0.000000,0.000000,0.073691,0.000000,0.013542,0.000000,0.912490,0.000000,6441,75400.0,0.20
1,근로복지공단,0.695667,0.000000,0.000000,0.228961,0.019995,0.000000,0.000000,0.054949,0.000000,0.000000,0.224451,0.000000,0.000000,0.000000,0.775140,0.000000,5817,9406.2,0.13
2,농협은행,0.275781,0.000000,0.000000,0.000000,0.000000,0.000000,0.516844,0.163050,0.031689,0.084182,0.229913,0.022778,0.021380,0.000000,0.631737,0.000000,6182,13100.0,0.15
3,현대카드,0.061863,0.000000,0.000000,0.220649,0.000000,0.365488,0.173676,0.000000,0.177817,0.000000,0.514205,0.356452,0.000000,0.097374,0.000000,0.029307,8737,2300.0,0.35
4,중소기업은행,0.511053,0.000000,0.000000,0.000000,0.000000,0.000000,0.481808,0.000000,0.000000,0.000000,0.258842,0.000000,0.000000,0.071889,0.656891,0.000000,10065,14800.0,0.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2498,유끼커뮤니케이션,0.000000,0.000000,0.000000,0.000000,0.000000,0.936469,0.000000,0.000000,0.000000,0.000000,0.000000,0.959034,0.000000,0.000000,0.000000,0.000000,4417,28.0,0.14
2499,투어이천,0.919112,0.010111,0.010109,0.010110,0.010113,0.010113,0.010110,0.010112,0.010111,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.942648,1314,108.9,1.36
2500,휴먼코아,0.000000,0.456919,0.000000,0.000000,0.000000,0.000000,0.013032,0.525660,0.000000,0.000000,0.311305,0.000000,0.000000,0.000000,0.000000,0.682863,3062,430.1,1.00
2501,에이치엔씨네트워크,0.000000,0.000000,0.000000,0.000000,0.296156,0.305233,0.000000,0.221588,0.170775,0.000000,0.453240,0.000000,0.044698,0.000000,0.000000,0.494197,3038,336.9,0.68
2502,현대엔지비,0.274784,0.036323,0.000000,0.355166,0.000000,0.000000,0.330947,0.000000,0.000000,0.000000,0.000000,0.017770,0.859055,0.023889,0.097414,0.000000,5898,633.4,0.33

In [117]:
df = df[df['turn_over_rate']<1]
error_firm = ['동원홈푸드','휠라홀딩스','트리','와디즈','키위컴퍼니','줌인터넷','시선인터내셔널','브이티코스메틱','유니슨이테크','씨엠비대전방송','서울비젼','더메인즈','조은시스템']

for i in error_firm:
    df = df[df.company_name != i]
df

,company_name,adv_topic_0,adv_topic_1,adv_topic_2,adv_topic_3,adv_topic_4,adv_topic_5,adv_topic_6,adv_topic_7,adv_topic_8,dadv_topic_0,dadv_topic_1,dadv_topic_2,dadv_topic_3,dadv_topic_4,dadv_topic_5,dadv_topic_6,average_salary,total_sale,turn_over_rate
0,국민건강보험공단,0.946027,0.000000,0.014878,0.000000,0.000000,0.000000,0.000000,0.033859,0.000000,0.000000,0.073691,0.000000,0.013542,0.000000,0.912490,0.000000,6441,75400.0,0.20
1,근로복지공단,0.695667,0.000000,0.000000,0.228961,0.019995,0.000000,0.000000,0.054949,0.000000,0.000000,0.224451,0.000000,0.000000,0.000000,0.775140,0.000000,5817,9406.2,0.13
2,농협은행,0.275781,0.000000,0.000000,0.000000,0.000000,0.000000,0.516844,0.163050,0.031689,0.084182,0.229913,0.022778,0.021380,0.000000,0.631737,0.000000,6182,13100.0,0.15
3,현대카드,0.061863,0.000000,0.000000,0.220649,0.000000,0.365488,0.173676,0.000000,0.177817,0.000000,0.514205,0.356452,0.000000,0.097374,0.000000,0.029307,8737,2300.0,0.35
4,중소기업은행,0.511053,0.000000,0.000000,0.000000,0.000000,0.000000,0.481808,0.000000,0.000000,0.000000,0.258842,0.000000,0.000000,0.071889,0.656891,0.000000,10065,14800.0,0.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,플레이스엠,0.000000,0.000000,0.000000,0.473520,0.000000,0.511511,0.000000,0.000000,0.000000,0.000000,0.000000,0.248392,0.000000,0.000000,0.000000,0.747261,3964,165.7,0.45
2496,서울신용평가정보,0.013902,0.013900,0.013898,0.013899,0.013902,0.888796,0.013901,0.013898,0.013903,0.028672,0.028670,0.028677,0.028646,0.028691,0.028706,0.827938,3878,466.7,0.54
2498,유끼커뮤니케이션,0.000000,0.000000,0.000000,0.000000,0.000000,0.936469,0.000000,0.000000,0.000000,0.000000,0.000000,0.959034,0.000000,0.000000,0.000000,0.000000,4417,28.0,0.14
2501,에이치엔씨네트워크,0.000000,0.000000,0.000000,0.000000,0.296156,0.305233,0.000000,0.221588,0.170775,0.000000,0.453240,0.000000,0.044698,0.000000,0.000000,0.494197,3038,336.9,0.68
2502,현대엔지비,0.274784,0.036323,0.000000,0.355166,0.000000,0.000000,0.330947,0.000000,0.000000,0.000000,0.000000,0.017770,0.859055,0.023889,0.097414,0.000000,5898,633.4,0.33

In [118]:
x_data = df.drop(['company_name','turn_over_rate', 'average_salary', 'total_sale'], axis = 1, inplace = False)

In [119]:
combined_data = pd.read_csv("/content/drive/MyDrive/bow_df.csv")

In [120]:

from sklearn.model_selection import train_test_split
combined_data = combined_data[combined_data['turn_over_rate']<1]
error_firm = ['동원홈푸드','휠라홀딩스','트리','와디즈','키위컴퍼니','줌인터넷','시선인터내셔널','브이티코스메틱','유니슨이테크','씨엠비대전방송','서울비젼','더메인즈','조은시스템']
for i in error_firm:
    combined_data = combined_data[combined_data.company_name != i]
combined_data.dropna(axis=0, inplace=True)
combined_data = combined_data.drop(['Unnamed: 0'], axis=1)
combined_data = fv_preprocessing(combined_data)
tor = combined_data['turn_over_rate']
combined_data.drop('turn_over_rate', axis=1, inplace=True)

In [122]:
combined_data = combined_data.drop(['company_name'], axis = 1, inplace = False)

In [123]:
combined_data = pd.concat([combined_data, x_data], axis=1)

In [124]:
train_input, test_input, train_target, test_target = train_test_split(combined_data, tor, test_size=0.1, random_state=42)

In [125]:
train_input

,adv,dadv,average_salary,total_sale,adv_topic_0,adv_topic_1,adv_topic_2,adv_topic_3,adv_topic_4,adv_topic_5,adv_topic_6,adv_topic_7,adv_topic_8,dadv_topic_0,dadv_topic_1,dadv_topic_2,dadv_topic_3,dadv_topic_4,dadv_topic_5,dadv_topic_6
2249,일이 본인 역량에따라 다르고 어떤사람 밑에서 일하냐에따라 일의강도가 달라짐 워라벨은...,"연봉이 낮음, 생각보다 비 체계적, 어떤상사를 맡게되냐에따라 본인 스팩이 달라짐 문...",6032,255.7,0.630613,0.000000,0.020975,0.000000,0.129349,0.000000,0.000000,0.217315,0.000000,0.000000,0.823971,0.000000,0.174236,0.000000,0.000000,0.000000
73,나름 복지가 있고 얼마전까지는 정상적으로 운용됨. 사람들하고 친해지면 일하는데에 큰...,보고를 위한 문서작업이 어마어마함. 불필요한 업무와 시간 소비가 있음. 보고체계도 ...,4608,735.6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.964409,0.000000,0.011049,0.011045,0.011050,0.011032,0.011046,0.933741,0.011038
2320,"연차를 윗사람 눈치 안보고 쓸 수 있음, 직원마다 맡은 업무가 확고해서 직원과 업무...","문제 발생 시 책임자가 존재는 하지만 책임을 져주지는 않음, 휴가비 없음, 지정된 ...",3110,100.4,0.177463,0.000000,0.000000,0.058688,0.020699,0.086759,0.000000,0.654597,0.000000,0.000000,0.032539,0.437868,0.012774,0.066847,0.143843,0.305716
109,이것저것 포함하면 급여수준이 괜찮다나름 괜찮은 사람들이 간간히 있다 작년까지 회사가...,고이다 못해 썩은물들이 득실하다때문에 젊은세대들은 성장하지못한다 커리어 무덤이라는게...,6082,5200.0,0.393137,0.000000,0.000000,0.000000,0.000000,0.000000,0.545115,0.000000,0.051948,0.221728,0.430663,0.015602,0.000000,0.225620,0.104882,0.000000
1388,"밥이 현대그린푸드껄로 맛있다, 직원들이 착하다.딱 이뿐이다. 자유로운 연차사용, 야...","윗사람들이 꼰대다, 회사가 나아진다고 하고 복지가 늘어난다고 하지만 실질적으로 나아...",4233,2783.3,0.000000,0.715661,0.000000,0.040912,0.052211,0.146340,0.000000,0.000000,0.043952,0.459991,0.000000,0.000000,0.083607,0.100425,0.000000,0.350409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1766,아이크림을 준다 통큰버스가 다닌다 돈을 많이 받을 수 있다 일이 어렵지 않다 밥을 ...,계약직만 뽑는다 시도때도 없는 현장 지원 책임전가 70~80년대 마인드 들에 꼰대들...,6830,1806.8,0.000000,0.531246,0.000000,0.000000,0.147981,0.000000,0.000000,0.223206,0.085210,0.072236,0.555588,0.000000,0.000000,0.364915,0.000000,0.000000
1182,식권 나와서 점심은 식당 4곳에서 골라먹을 수 있음사상역 근처라 교통이 편리함 부산...,"모든 것, 근무시간에는 전화 받느냐고 업무 못하고 퇴근시간 되서야 내 업무를 할 ...",5046,2544.7,0.000000,0.228199,0.000000,0.000000,0.469188,0.093154,0.208160,0.000000,0.000000,0.703111,0.000000,0.000000,0.012351,0.098791,0.000000,0.184967
1220,워라밸 - 특히 유연근무가 매우 잘되어 있음적당한 연봉 - 어디가서 굶어죽지는 않을...,"근무지가 정말 오지 중의 오지에 있다 삼척, 하동 등등.. 나머지는 그래도 살만하지...",8665,5700.0,0.519181,0.000000,0.000000,0.000000,0.000000,0.000000,0.477825,0.000000,0.000000,0.104650,0.076603,0.000000,0.000000,0.078195,0.739248,0.000000
1398,좋은 사람이 많았다.구내식당이 있어서 밥값 아낄 수 있었다.사내 카페가 싸다. 연차...,직무에 맞지않는 업무연봉이 매우매우매우 낮음팀끼리 화합해도 모자랄판에 서로 기싸움과...,4719,323.1,0.000000,0.014201,0.000000,0.000000,0.857450,0.123988,0.000000,0.000000,0.000000,0.572473,0.000000,0.021814,0.000000,0.151371,0.000000,0.253143
931,사람이 많아서 은근히 장점이 될 수 있음 개인주의 분위기 같아보이지만 큰 텃세는 없...,엘리베이터 타려면 기다리는 시간이 소요되서 힘들었음 지각하면 안되니 더 부담되고 일...,3720,100.0,0.000000,0.000000,0.000000,0.341091,0.000000,0.654572,0.000000,0.000000,0.000000,0.000000,0.000000,0.681195,0.000000,0.000000,0.000000,0.310026

In [126]:
test_input

,adv,dadv,average_salary,total_sale,adv_topic_0,adv_topic_1,adv_topic_2,adv_topic_3,adv_topic_4,adv_topic_5,adv_topic_6,adv_topic_7,adv_topic_8,dadv_topic_0,dadv_topic_1,dadv_topic_2,dadv_topic_3,dadv_topic_4,dadv_topic_5,dadv_topic_6
1768,많은 업무를 경험할 수 있고 생각지도 못했던 업무에 대해서도 견문을 넓힐 수 있는 ...,잡플래닛에 있는 연봉이 실제 연봉. 뭐 성과금 나오면 얼마 되겠지 하는 행복회로는 ...,5933,2063.4,0.000000,0.196448,0.00000,0.000000,0.305526,0.000000,0.104962,0.000000,0.389694,0.937825,0.000000,0.000000,0.000000,0.047639,0.000000,0.011237
549,"업계 대비 높은 연봉, 수업 스케줄이 유연한 편이라 오후 출근 가능 업무자율성이 높...",아무래도 아이들과 학부모님을 상대해야하는 직업이기 때문에 힘이 들 수 밖에 없고 저...,4247,1011.3,0.152174,0.000000,0.00000,0.312448,0.000000,0.000000,0.086134,0.441285,0.000000,0.074484,0.159760,0.172933,0.088749,0.038492,0.107954,0.357628
1536,휴가 자유지방 기업 대비 초봉 높은편자동차계열로 복지도 좋은편 점심밥이 제공된다.연...,지역이 조금 아쉬움.. 다만 차량만 있으면 위치가 좋음천안 번화가에서 차로 20분거...,6032,2201.5,0.000000,0.437977,0.00000,0.000000,0.218135,0.000000,0.341878,0.000000,0.000000,0.437913,0.000000,0.000000,0.372349,0.023096,0.000000,0.165360
44,"1. 자회사 탑(급여, 복지)2. 현대라는 타이틀3. 구내식당4. 훌륭한 전산5. ...",1. 보수적인 기업 문화2. 구린 사원증3. 업무환경 별로4. 화장실 별로 업무량 ...,5601,719.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.737443,0.220844,0.035107,0.232291,0.094388,0.066578,0.000000,0.165848,0.438523,0.000000
1509,"연차를 생각보다 자유롭게 쓸 수 있으며, 식사도 생각보다 괜찮게 나오는 듯 연차를...",진천군에 있어서 거리가 출퇴근하기에는 조금 멀다. 자차가 없는 사람은 사내 기숙사 ...,4750,616.1,0.106381,0.000000,0.00000,0.000000,0.723403,0.000000,0.157626,0.000000,0.000000,0.446815,0.000000,0.000000,0.152364,0.395459,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1884,1. 최근 호황임2. 월급이 밀리지않고 나옴3. 식사제공4. 자녀 대학 학자금 90...,1. 자율적의사보다 무조건 상급자 지시대로 업무를 진행해야함2. 정말 수동적으로 일...,6073,5627.7,0.000000,0.235737,0.00000,0.000000,0.265523,0.000000,0.488502,0.000000,0.000000,0.552670,0.000000,0.000000,0.147946,0.144871,0.000000,0.152433
84,"돈도 어느정도 주고 종각 그랑서울에 위치하여 접근성이 좋다 자유롭다, 직원들이 잘생...",사옥이없다. 그랑서울 임대해서 회사에 별다른 복지가 없다 (사옥관련) 나머지 다. ...,9467,6200.0,0.627092,0.000000,0.20367,0.000000,0.000000,0.117712,0.042971,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.987874,0.000000,0.000000
1881,연봉 및 성과급이 아무래도 정유사이다보니 높다. 자율좌석제로 인하여 선택하여 앉을 ...,연봉이 높은 편이지만 일 많은 부서는 정말 일 많다. 식당 이용이 좀 불편할 수 있...,2691,4.9,0.000000,0.000000,0.00000,0.479084,0.000000,0.000000,0.394697,0.000000,0.120467,0.014195,0.561702,0.135889,0.090197,0.195336,0.000000,0.000000
1514,사회생활을 하기위해 어떻게하면 직장에서 윗사람에게 예쁨받을 수 있는지 배울 수 있다...,비오는날 천장에서 비가 새는 사옥. 직장내에서 슬리퍼를 신으면 예의에 오긋난다고 사...,4247,902.9,0.000000,0.000000,0.00000,0.000000,0.000000,0.870168,0.000000,0.125860,0.000000,0.000000,0.000000,0.011833,0.000000,0.114768,0.000000,0.872388
178,나름 체계있음 직원 규모도 있고 역사도 있어 이력에 당당한 한줄 가능한 회사. 신입...,"문구가 야박하다. 웬만한건 내돈내산해야하고 편하게 포스트잇 하나 가져다 쓸수 없음,...",4835,1466.8,0.000000,0.129082,0.00000,0.345985,0.000000,0.055039,0.319863,0.147215,0.000000,0.164996,0.109552,0.255941,0.000000,0.026332,0.000000,0.441861

In [127]:
train_input = fv_preprocessing(train_input)

In [128]:
train_adv_text = train_input['adv'].to_numpy()
train_dadv_text = train_input['dadv'].to_numpy()

In [129]:
test_adv_text = test_input['adv'].to_numpy()
test_dadv_text = test_input['dadv'].to_numpy()

In [130]:
financial_train1=train_input['average_salary'].to_numpy()
financial_train2=train_input['total_sale'].to_numpy()
financial_test1=test_input['average_salary'].to_numpy()
financial_test2=test_input['total_sale'].to_numpy()

In [131]:
# np.array2string(train_adv_text)
# np.array2string(train_dadv_text)
# np.array2string(test_adv_text)
# np.array2string(test_dadv_text)

In [132]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

adv_tfidfvector = TfidfVectorizer()
adv_train = adv_tfidfvector.fit_transform(train_adv_text)
adv_test = adv_tfidfvector.transform(test_adv_text)

In [133]:
dadv_tfidfvector = TfidfVectorizer()
dadv_train = dadv_tfidfvector.fit_transform(train_dadv_text)
dadv_test = dadv_tfidfvector.transform(test_dadv_text)

In [134]:
financial_train1 = financial_train1.reshape(-1, 1)
financial_train2 = financial_train2.reshape(-1, 1)
financial_test1 = financial_test1.reshape(-1, 1)
financial_test2 = financial_test2.reshape(-1, 1)

In [135]:
financial_train1 = financial_train1.astype(float)
financial_train2 = financial_train2.astype(float)
financial_test1 = financial_test1.astype(float)
financial_test2 = financial_test2.astype(float)

In [136]:
train_input.iloc[:, -16:]

,adv_topic_0,adv_topic_1,adv_topic_2,adv_topic_3,adv_topic_4,adv_topic_5,adv_topic_6,adv_topic_7,adv_topic_8,dadv_topic_0,dadv_topic_1,dadv_topic_2,dadv_topic_3,dadv_topic_4,dadv_topic_5,dadv_topic_6
2249,0.630613,0.000000,0.020975,0.000000,0.129349,0.000000,0.000000,0.217315,0.000000,0.000000,0.823971,0.000000,0.174236,0.000000,0.000000,0.000000
73,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.964409,0.000000,0.011049,0.011045,0.011050,0.011032,0.011046,0.933741,0.011038
2320,0.177463,0.000000,0.000000,0.058688,0.020699,0.086759,0.000000,0.654597,0.000000,0.000000,0.032539,0.437868,0.012774,0.066847,0.143843,0.305716
109,0.393137,0.000000,0.000000,0.000000,0.000000,0.000000,0.545115,0.000000,0.051948,0.221728,0.430663,0.015602,0.000000,0.225620,0.104882,0.000000
1388,0.000000,0.715661,0.000000,0.040912,0.052211,0.146340,0.000000,0.000000,0.043952,0.459991,0.000000,0.000000,0.083607,0.100425,0.000000,0.350409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1766,0.000000,0.531246,0.000000,0.000000,0.147981,0.000000,0.000000,0.223206,0.085210,0.072236,0.555588,0.000000,0.000000,0.364915,0.000000,0.000000
1182,0.000000,0.228199,0.000000,0.000000,0.469188,0.093154,0.208160,0.000000,0.000000,0.703111,0.000000,0.000000,0.012351,0.098791,0.000000,0.184967
1220,0.519181,0.000000,0.000000,0.000000,0.000000,0.000000,0.477825,0.000000,0.000000,0.104650,0.076603,0.000000,0.000000,0.078195,0.739248,0.000000
1398,0.000000,0.014201,0.000000,0.000000,0.857450,0.123988,0.000000,0.000000,0.000000,0.572473,0.000000,0.021814,0.000000,0.151371,0.000000,0.253143
931,0.000000,0.000000,0.000000,0.341091,0.000000,0.654572,0.000000,0.000000,0.000000,0.000000,0.000000,0.681195,0.000000,0.000000,0.000000,0.310026

In [137]:
train_last_16_columns = train_input.iloc[:, -16:].values
test_last_16_columns = test_input.iloc[:, -16:].values

In [138]:
from scipy.sparse import hstack # tf-idf로 변환된 텍스트 데이터와 금융 데이터를 연결
X_train = hstack([adv_train, dadv_train, financial_train1, financial_train2, train_last_16_columns])  # 텍스트 데이터와 금융 데이터를 수평으로 연결
X_test = hstack([adv_test, dadv_test,financial_test1, financial_test2, test_last_16_columns])    # 테스트 데이터에 대해서도 동일하게 수행

In [139]:
y_train = train_target.to_numpy()
y_test = test_target.to_numpy()

In [140]:
# Linear Regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error, r2_score



lr_reg = LinearRegression()
lr_reg.fit(X_train, y_train)

ridge_reg = Ridge()
ridge_reg.fit(X_train, y_train)

lasso_reg = Lasso()
lasso_reg.fit(X_train,y_train)

models = [lr_reg, ridge_reg, lasso_reg]
get_rmses(models)
print('\n')
get_r2scores(models)

LinearRegression  RMSE:  0.162
Ridge  RMSE:  0.16
Lasso  RMSE:  0.183


LinearRegression  R2SCORE:  0.319
Ridge  R2SCORE:  0.341
Lasso  R2SCORE:  0.131

In [ ]:
from sklearn.model_selection import GridSearchCV

def print_best_params(model, params):
    grid_model = GridSearchCV(model, param_grid=params,
                              scoring='neg_mean_squared_error', cv=5)
    grid_model.fit(X_train,y_train)
    mse = -1 * grid_model.best_score_
    rmse = np.sqrt(-1*grid_model.best_score_)
    print('train: {0} After 5 CV, best average MSE: {1}, best average RMSE: {2}, best alpha: {3}'.format(model.__class__.__name__,np.round(mse,4),
                                                                           np.round(rmse,4),grid_model.best_params_))

    grid_score = grid_model.score(X_test, y_test)
    mse = -1 * grid_score
    rmse = np.sqrt(-1*grid_score)
    print('test: {0} After 5 CV, best average MSE: {1}, best average RMSE: {2}, best alpha: {3}'.format(model.__class__.__name__,np.round(mse,4),
                                                                           np.round(rmse,4),grid_model.best_params_))

    grid_model = GridSearchCV(model, param_grid=params,
                              scoring='neg_mean_absolute_error', cv=5)
    grid_model.fit(X_train,y_train)
    mae = -1 * grid_model.best_score_
    print('train: {0} After 5 CV, best average MAE: {1}'.format(model.__class__.__name__,np.round(mae,4)))
    print('test: {0} After 5 CV, best average MAE: {1}'.format(model.__class__.__name__,np.round(-1*grid_model.score(X_test, y_test),4)))



    grid_model = GridSearchCV(model, param_grid=params,
                              scoring='r2', cv=5)
    grid_model.fit(X_train,y_train)
    r2_score = grid_model.best_score_
    print('train: {0} After 5 CV, best average R2 score: {1}'.format(model.__class__.__name__,np.round(r2_score,4)))
    print('test: {0} After 5 CV, best average R2 score: {1}'.format(model.__class__.__name__,np.round(grid_model.score(X_test, y_test),4)))

ridge_params = {'alpha':[0.05, 0.1, 1, 5, 8, 10, 12, 15, 20]}
lasso_params = {'alpha':[0.001, 0.005, 0.008, 0.05, 0.03, 0.1, 0.5, 1, 5, 10]}
print_best_params(ridge_reg,ridge_params)
print_best_params(lasso_reg,lasso_params)